name: digidoc
description: "Documents management app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  image_picker: ^1.1.2
  image: ^4.5.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  camera: ^0.11.1
  gal: ^2.3.1
  image_editor: ^1.0.0
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  mockito: ^5.4.0
  flutter_gen: ^5.3.0

flutter:
  assets:
    - assets/
  uses-material-design: true


