name: DigiDoc
description: "Documents management app."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_document_scanner: ^0.4.0
  google_mlkit_commons: ^0.11.0
  image: ^4.5.3
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  camera: ^0.11.1
  gal: ^2.3.1
  image_editor: ^1.0.0
  local_auth: ^2.3.0
  http: ^1.3.0
  flutter_riverpod: ^2.6.1
  go_router: ^15.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.4
  tflite_flutter: ^0.11.0
  intl: ^0.19.0
  flutter_pdfview: ^1.3.2
  share_plus: ^11.0.0
  printing: ^5.12.0
  flutter_secure_storage: ^9.0.0
  permission_handler: ^12.0.0+1
  diacritic: ^0.1.5
  timezone: ^0.10.0
  flutter_background_service: ^5.1.0
  flutter_local_notifications: ^19.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  mockito: ^5.4.0
  flutter_gen: ^5.3.0
  image_picker: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt
    - assets/defaultDocs.txt

flutter_icons:
  android: true
  ios: true
  adaptive_icon_background: "#000000"